Wire up e2e tests into meson
But make sure these are part of a suite that we don't run from the
packaging.

diff --git a/e2e/common b/e2e/common
--- a/e2e/common
+++ b/e2e/common
@@ -1,17 +1,17 @@
 #!/bin/bash
 
 find_build_directory() {
-  local build_dirs=(*/.ninja_log)
+  local f build_dirs=("$PWD"/.ninja_log "$PWD"/*/.ninja_log)
 
-  if [[ ! -e ${build_dirs[0]} ]]; then
-    echo "error: No build directory found. Have you run 'meson build' yet?" >&2
-    return 1
-  elif (( ${#build_dirs[*]} > 1 )); then
-    echo "error: Multiple build directories found. Unable to proceed." >&2
-    return 1
-  fi
+  for f in "${build_dirs[@]}"; do
+    if [[ -e $f ]]; then
+      printf '%s\n' "${f%/*}"
+      return 0
+    fi
+  done
 
-  printf '%s\n' "${build_dirs[0]%/*}"
+  echo "error: No build directory found. Have you run 'meson build' yet?" >&2
+  return 1
 }
 
 assert_directory_exists() {
